//Teste de Requisições REST - Categorias
@baseURL = http://localhost:4000
@id = 60b9bc8f3b32e311ce2a79db
##
// GET - Lista todas as categorias
GET {{baseURL}}/moveis
Content-Type: application/json

###
// GET - Lista apenas uma categoria pelo id
GET {{baseURL}}/moveis/{{id}}
Content-Type: application/json

###
// POST - Inclui uma nova categoria
POST {{baseURL}}/moveis
Content-Type: application/json

{
    "movel": "sofá",
    "comodo": "sala",
    "cor": "preto",
    "tamanho": "grande",
    "valor": 212
}

### 
// DELETE - Apaga uma categoria através do id informado
DELETE {{baseURL}}/moveis/{{id}}
Content-Type: application/json

###
// PUT - Altera uma categoria pelo ID
PUT {{baseURL}}/moveis
Content-Type: application/json

{
   
}


###
// PUT - Altera uma categoria pelo ID - INVÁLIDO
PUT {{baseURL}}/moveis
Content-Type: application/json

{
    "_id": "9999", 
    "nome": "Cantinas Italianas 2",
    "status": "ativo"
}